from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'web2print.views.home', name='home'),
    url(r'^/*', include("core.urls")),
    url(r'^/*', include("banner.urls")),
    url(r'^/*', include("article_category.backend_urls")),
    url(r'^/*', include("article.backend_urls")),
    url(r'^/*', include("format.backend_urls")),
    url(r'^/*', include("paper_type.backend_urls")),
    url(r'^/*', include("printing_price.backend_urls")),
    url(r'^/*', include("printer.backend_urls")),
    url(r'^/*', include("paper_finish.backend_urls")),
    url(r'^/*', include("paper_weight.backend_urls")),
    url(r'^/*', include("product_category.backend_urls")),
    url(r'^/*', include("product_subcategory.backend_urls")),
    url(r'^/*', include("paper.backend_urls")),
    url(r'^/*', include("press.backend_urls")),
    url(r'^/*', include("plastic.backend_urls")),
    url(r'^/*', include("flexion.backend_urls")),
    url(r'^/*', include("binding.backend_urls")),
    url(r'^/*', include("product.backend_urls")),
    url(r'^/*', include("cart.frontend_urls")),
    url(r'^/*', include("article.frontend_urls")),
    url(r'^/*', include("user.frontend_urls")),
    url(r'^/*', include("product.frontend_urls")),
    url(r'^/*', include("product_subcategory.frontend_urls")),
    url(r'^/*', include("product_category.frontend_urls")),
    url(r'^$', 'frontpage.views.index', name="index-page"),
)
